
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - name: Check if gh-actions-ec2-test is running
      id: check_pm2
      run: |
        if pm2 list | grep -wq "gh-actions-ec2-test" | awk '{print $18}' | grep -wq "online"; then
          echo "::set-output name=is_running::true"
        else
          echo "::set-output name=is_running::false"
        fi
    - name: Start gh-actions-ec2-test if not running
      # id: start_pm2  
      if: steps.check_pm2.outputs.is_running != 'true'
      run: sudo pm2 start /home/ec2-user/actions-runner/_work/gh-actions-ec2-test/gh-actions-ec2-test --name=gh-actions-ec2-test
      # echo "::set-output name=started::true"

    - name: Restart gh-actions-ec2-test
      # if: steps.check_pm2.outputs.is_running == 'true'
      run: sudo pm2 restart gh-actions-ec2-test
